<?php
/**
 * Agenda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Agenda extends BaseAgenda
{
   //Alias da Tabela
   private $table_alias = "Agenda a";
   
   //Retorna os dados da Agenda
   public function getAgenda($limit=4){
   
     try{
	 
	     //Instancia a classe de Manutenção do Doctrine
	     $manager = Doctrine_Manager::getInstance();
		 //Solicita a conexão atual com o banco
		 $dbh = $manager->getCurrentConnection();
		 
		 //SQL a ser executado
		 $sql = "SELECT sf_getAgenda(".$limit.")";
		 
		 //Prepara a query
		 $sth = $dbh->prepare($sql);
		 //Executa a query
		 $sth->execute();
		 //Recebe o resultado
		 $result = $sth->fetch(PDO::FETCH_ASSOC);
		 
		 //Requisita a biblioteca do JSON
		 LibFactory::getInstance(null,null,'Zend/Json.php');
		 //Transforma o json recebido na query em um Array
		 return Zend_Json::decode($result['sf_getagenda']);
	 
	 }catch(Exception $e){	 
	    //Exibe a mensagem da exceção
	    //echo $e->getMessage();		
		//exit();
	 }   
   }   
}