<?php
/**
 * Album
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Album extends BaseAlbum
{
   //Table Alias
   private $table_alias = "Album al";

   //Busca um album com base na sua tag
   public function getAlbumByTag($tag){
		
		try{
	    
	       $query = Doctrine_Query::create()
		           ->select('*')
				   ->from($this->table_alias)
				   ->where('al.tag = ?',trim($tag));
				   
		   if($query->count() > 0){		   
		   
			   $recordset = $query->execute();
			   return $recordset[0];	   
			   
		   }else{
			   
			   return false;
		   }
	   
	   }catch(DOCTRINE_EXCEPTION $e){
	   
	      //Tratar Exceção		  
	      return false;
	   }
   }
   
   //Busca os albuns
   public function getAlbuns($limit=null,$orderby=null){
		
		try{
	    
	       $query = Doctrine_Query::create()
		           ->select('*,gl.imagem')
				   ->from($this->table_alias)
				   ->innerJoin('al.Galeriafotos gl');
			
           //Verifica se um limite foi especificado			
		   if(!is_null($limit)){
		       //Adiciona o limite
		       $query->limit($limit);
		   }
		   
		   //Verifica se uma ordenação foi especificada
		   if(!is_null($orderby)){
		       //Adiciona o orderby
		       $query->orderby($orderby);
		   }
				   
		   if($query->count() > 0){		   
		   
			   $recordset = $query->execute();			   
			   return $recordset;	   
			   
		   }else{
			   
			   return false;
		   }
	   
	   }catch(DOCTRINE_EXCEPTION $e){	      
	      //Tratar Exceção		  
	      return false;
	   }
   }
}