<?php
/**
 * Banners
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Banners extends BaseBanners
{
   //Table Alias
   private $table_alias = "Banners b";

   //Busca os banners da base de dados
   public function getBanners(){
		
		try{
	    
	       $query = Doctrine_Query::create()
		           ->select('*')
				   ->from($this->table_alias);
				   
		   if($query->count() > 0){		   
		   
			   $recordset = $query->execute();
			   return $recordset;	   
			   
		   }else{
			   
			   return false;
		   }
	   
	   }catch(DOCTRINE_EXCEPTION $e){
	   
	      //Tratar Exceção		  
	      return false;
	   }
   }
}