<?php
/**
 * Cargos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cargos extends BaseCargos
{

   //Alias da tabela
    private $table_alias = "Cargos car";
	
    public function getCargos(){
	   
	   try{	  
	   
	     //Monta a query principal
	     $query = Doctrine_Query::create()
                  ->select('*')
                  ->from($this->table_alias);				  
				  
		 //Executa a Query	         
		 return $query->execute();			 
		 
		 }catch(DOCTRINE_EXCEPTION $e){		 
		    //Tratamento da Exceção			
		 }
	}
}