<?php
/**
 * Cidades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cidades extends BaseCidades
{
   private $table_alias = "Cidades city";

    public function getCidades($estado=null){
	
	   try{
	    
	       $query = DOCTRINE_QUERY::create()
		           ->select('*')
				   ->from($this->table_alias);				   
				   
		   if(!is_null($estado)){
		   
		       $query->where('idestado = ?',$estado);
		   }
		   
           $recordset = $query->execute()->toArray();			   
		   return $recordset;
	   
	   }catch(DOCTRINE_EXCEPTION $e){
	   
	      //Tratar Exceção		  
	      return false;
	   }
	}
}