<?php
/**
 * Cursos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cursos extends BaseCursos
{
    //Alias da tabela
    private $table_alias = "Cursos cur";
	
    public function listarCursosDisponiveis(){
	   
	   try{
	   
	     //SubQuery
	     $subquery = Doctrine_Query::create()
                  ->select('cast((sum(extract(epoch from submod.cargahoraria))/60/60) as varchar)')
                  ->from('Cursos subcur')
				  ->innerJoin('subcur.CursosHasModulos subchm')
				  ->innerJoin('subchm.Modulos submod')				  
                  ->where('subchm.idcurso = chm.idcurso');				  
	   
	     //Monta a query principal
	     $query = Doctrine_Query::create()
                  ->select('cur.nome, chm.idcurso , mod.titulo , ('.$subquery->getDql().') as total_horas')
                  ->from($this->table_alias)
				  ->innerJoin('cur.CursosHasModulos chm')
				  ->innerJoin('chm.Modulos mod');
				  
		 //Executa a Query	         
		 return $query->execute();			 
		 
		 }catch(DOCTRINE_EXCEPTION $e){		 
		    //Tratamento da Exceção             			
		 }
	}
	
	public function getCurso($id){
   
       try{	    	  
	   
	     //Monta a query principal
	     $query = Doctrine_Query::create()
                  ->select('*')
                  ->from($this->table_alias)
				  ->where('cur.id = ?',$id);
				  
			//Executa a query
			$recordset = $query->execute();
			//Retorna a unidade selecionada
			return (isset($recordset[0]) ? $recordset[0] : "");		 
		 
		 }catch(DOCTRINE_EXCEPTION $e){		 
		    return "";
		 }
   }
}