<?php

/**
 * Empresaconvenio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Empresaconvenio extends BaseEmpresaconvenio
{
  //Alias da Tabela
  private $table_alias = "Empresaconvenio ec";

  public function listarConvenios(){
  
      try{
	  
	     $query = Doctrine_Query::create()
                  ->select('*')		 
				  ->from($this->table_alias);

         return $query->execute(); 				  
	  }      
	  catch(DOCTRINE_EXCEPTION $e){
	  
	     //Tratamento da Exceção
	  }	  
  }
}