<?php

/**
 * Instituicao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Instituicao extends BaseInstituicao
{
    public function buscarInformacoesInstitucionais(){
	
	    try{
		
		   return $this->getTable()->find(1);
		
		}catch(DOCTRINE_EXCEPTION $e){
		
		   //Tratamento da Exceção
		}
	}
}