<?php

/**
 * Modulos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Modulos extends BaseModulos
{
    private $table_alias = "Modulos mod";

    public function getModuloById($id){
	
	   try{
	    
	       $query = Doctrine_Query::create()
		           ->select('*')
				   ->from($this->table_alias)
				   ->where('mod.id = ?',$id);
				   
           if($query->count() == 0){		      
		      return false;
		   }
		   
           $recordset = $query->execute();	
		   return $recordset[0];
	   
	   }catch(DOCTRINE_EXCEPTION $e){
	   
	      //Tratar Exceção		  
	      return false; //Retorna falso indicando que o modulo não foi encontrado
	   }
	}
}