<?php
/**
 * Nivelamentonotas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Nivelamentonotas extends BaseNivelamentonotas
{
   //Álias da tabela
   private $table_alias = "Nivelamentonotas nn";
   
   public function gravarNota($nota){
      
	  try{
	 
	      //Seta o id do candidato
		  $this->idcandidato = $_SESSION['idCandidato'];
	      //Seta a nota
		  $this->nota = $nota;
		  //Seta a data
		  $this->dia = date("Y-m-d");
	      //Salva os dados
		  $this->save();
		  //Retorna positivo
		  return true;
	  
	  }catch(Exception $e){
	     //echo $e->getMessage();
		 //Retorno negativo
		 return false;
	  }
   }
}