<?php
/**
 * Nivelamentocandidatos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Nivelamentocandidatos extends BaseNivelamentocandidatos
{
	private $table_alias = "Nivelamentocandidatos nc";
	
	public function cadastrar($parametros){
	
	      try{   
		  
	      //Recebe os valores informados
	      $campos_valores = $this->setValues($this,$parametros,false);		  
		  
		  //Seta os dados no objeto
		  foreach($campos_valores as $campo => $valor){
		  
		     $this->$campo = $campos_valores->$campo;
		  }
		  
		  //Salva os dados
		  $this->save();
		  //Retorna true em caso de sucesso
		  return true;
	   
	   
	   }catch(DOCTRINE_EXCEPTION $e){
	      //echo $e->getMessage(); exit();
	      //Tratar exceção	
          return false;		  
	   }	 
	}
	
	public function verificarEmail($parametros){
		
		try{

		  $query = Doctrine_Query::create()
				   ->select('nc.id,nc.nome,nc.email')
				   ->from($this->table_alias)
				   ->where('nc.email = ?',$parametros['email']);
				   
           if($query->count() > 0){
		      $recordset = $query->execute();
			  return $recordset;
		   }else{			  
			  return false;
		   }				   
	   
	   }catch(DOCTRINE_EXCEPTION $e){
	      //echo $e->getMessage(); exit();
	      //Tratar exceção	
          return false;		  
	   }
	}
}