<?php
/**
 * Noticia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Noticia extends BaseNoticia
{
    private $table_alias = "Noticia n";

    public function BuscarNoticias($orderby=null,$limit=null,$pagina_atual=null){
	
	   try{
	    
	       $query = Doctrine_Query::create()
		           ->select('n.id,n.titulo,SUBSTR(n.texto, 0, 200) as texto,n.imagem,n.manchete')
				   ->from($this->table_alias);
				
            //Verifica se foi solicitado ordenação na Query				
			if(!is_null($orderby)){
			
               //Ordena pelo critério informado			
			   $query->orderby($orderby);
			}	   
			
			//Verifica se foi solicitado um limite de registros(Sem paginação)
			if(!is_null($limit)){
			
               //Limita os registros
			   $query->limit($limit);
			   
			}else{
				    
			    //Define a url da paginação
                $url_paginacao = DEFAULT_URL."noticias/index/pagina/";				
				//Executa a paginação de registros
				$result_by_pagination = HelperFactory::getInstance('pagination')->create($url_paginacao, $query , $pagina_atual, 5,3);				
				//Retorna o resultado da paginação
		        return $result_by_pagination;
			}	   
				   
		   //Executa a Query		   
		   return $query->execute();		   
	   
	   }catch(DOCTRINE_EXCEPTION $e){
	   
	      //Tratar Exceção
	   }
	}
	
	public function getNoticiaById($id){
	
	   try{
	       
		   //Localiza a noticia pelo id
		   $registro = $this->getTable()->find($id);		   
			
           //Verifica se a noticia foi encontrada			
           if($registro === false){		      
		      return false;
		   }		   
		   
		   //Verifica se o usuário da sessão atual já visualizou esta notícia
		   if(!isset($_SESSION['noticias_visualizadas'][$registro->id])){
		       
               //Incrementa o rank de visualização da noticia
		       $registro->rank = $registro->rank + 1; 			   
			   //Salva as alterações
		       $registro->save();
			   /*Acrescenta o id da noticia visualizada na sessão, 
			     indicando que o usuário da sessão já viu essa noticia
			   */
			   $_SESSION['noticias_visualizadas'][$registro->id] = $registro->id;	
		   }
           
		   //Retorna os dados da noticia
		   return $registro;
	   
	   }catch(DOCTRINE_EXCEPTION $e){
	   
	      //Tratar Exceção		  
	      return false; //Retorna falso indicando que a noticia não foi encontrada
	   }
	}
}