<?php
/**
 * SacAssuntos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SacAssuntos extends BaseSacAssuntos
{

    //Alias da tabela
    private $table_alias = "SacAssuntos sa";
	
    public function buscarAssuntos($id=null){
	   
	   try{	  
	   
	     //Monta a query principal
	     $query = Doctrine_Query::create()
                  ->select('*')
                  ->from($this->table_alias);				  
			
         //Se passar ID pesquisa pelo ID			
		 if(!is_null($id)){
		    //Adiciona o filtro por ID
			$query->where('sa.id = ?',$id);
			//Executa a Query
			$recordset = $query->execute();
			//Retorna o Assunto Selecionado
		    return $recordset[0];			 	
		 }		  
				  
		 //Executa a Query - Retornando todos os assuntos cadastrados no banco de dados	         
		 return $query->execute();			 
		 
		 }catch(DOCTRINE_EXCEPTION $e){		 
		    return false;			
		 }
	}
}