<?php
/**
 * Trabalheconosco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Trabalheconosco extends BaseTrabalheconosco
{
	//Alias da Tabela
    private $table_alias = "Trabalheconosco tc";    

	public function cadastrar($parametros){
	
	      try{   
		  
	      //Recebe os valores informados
	      $campos_valores = $this->setValues($this,$parametros,false);		  
		  
		  //Seta os dados no objeto
		  foreach($campos_valores as $campo => $valor){
		  
		     $this->$campo = $campos_valores->$campo;
		  }
		  
		  //Salva os dados
		  $this->save();
		  //Retorna true em caso de sucesso
		  return true;
	   
	   
	   }catch(DOCTRINE_EXCEPTION $e){
	   
	      //Tratar exceção	
          return false;		  
	   }	 
	}
}