<?php

/**
 * Turno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Turno extends BaseTurno
{
    private $table_alias = "Turno tur";

    public function getTurnos(){
	
	   try{
	    
	       $query = Doctrine_Query::create()
		           ->select('*')
				   ->from($this->table_alias);				   
		   
           $recordset = $query->execute();	
		   return $recordset;
	   
	   }catch(DOCTRINE_EXCEPTION $e){
	   
	      //Tratar Exceção		  
	      return false;
	   }
	}
}