<?php
/**
 * Usuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Usuario extends BaseUsuario
{
    //Alias da Tabela
    private $table_alias = "Usuario u";

	public function getProfessorByUnidade($idunidade){      
	   
		   try{	    	  
		   
			 //Monta a query principal
			 $query = Doctrine_Query::create()
					  ->select('u.nome')
					  ->from($this->table_alias)
					  ->innerjoin('u.Unidades unit')
					  ->innerjoin('u.Perfis p')
					  ->where('unit.id = ?',$idunidade)
					  ->andwhere('p.id = 2');
					  
			 //Executa a Query	         
			 return $query->execute()->toArray();			 
			 
			 }catch(DOCTRINE_EXCEPTION $e){		 
				//Tratamento da Exceção	                
			 }
	   }
}